Added Non-Blind Mode Options
millanlaboratory/PatientAllocationSinergia pull request #3
Opened 2020-10-20 03:20 UTC by zrhernan

The following updates were made to the repository:
 - Decision message box at the start to indicate whether to view allocator in 'blind' or 'non-blind' mode
 - If in 'non-blind' mode, the following features were added for the user's convenience when adding a new subject entry:
   - Dialog message box showing results of the Frane algorithm which includes: final group placement for the new entry as well as group-wise and group-field-wise probability values
   - Second decision message box asking whether the user wishes to keep the current group placement or switch new subject entry to the opposite group
   - Third dialog message box confirming the new entry group placement
 - In either blind/non-blind mode, a new feature was added to code such that 'BCI group' subject IDs matched to a 'Sham group' subject are saved and compared so that a 'BCI group' subject can be paired to ONLY ONE 'Sham group' subject
 - If in 'blind' mode, the allocator operates as originally designed, with automatically group placement of a new subject entry that is blind to the user inputting subject data

2020-10-20 06:02 UTC, Ruijan requested changes
Nice feature but please be careful to keep the MVC pattern intact.
The Subject and SubjectFactory must not know anything about the GUI.

2020-10-20 06:02 UTC, Ruijan commented on patientalloc/src/Database/Database.py
> +        # print(self.entries)
Remove commented out code

2020-10-20 06:02 UTC, Ruijan commented on patientalloc/src/Database/Subject/SubjectFactory.py
> +        self.gui = currentGui
The subject factory should not know about the GUI. It is independent of the way the database is displayed. Move the display you added to the DatabaseLoaderDisplay.py in GUI and implement it in the add_subject method.

2020-10-20 06:02 UTC, Ruijan commented on patientalloc/src/GUI/GUI.py
> +        viewmode = self.getViewMode()
There is an admin version of the GUI. The idea was to not forbid users to see the results except those who can run it in admin mode. It's the first argument passed to the GUI creation in patientalloc/__init__.py.

2020-10-20 06:02 UTC, Ruijan commented on build/lib.linux-x86_64-2.7/patientalloc/src/Database/Subject/SubjectFactory.py
>  import patientalloc
It seems that the whole build folder has been added to the commit.
I forgot to add the build folder to the .gitignore. Could you add it?
Thanks

2020-11-04 20:00 UTC, zrhernan commented on patientalloc/src/Database/Subject/SubjectFactory.py
> +        self.gui = currentGui
I implemented these changes such that all GUI definitions are called from the GUI.py script in the add_subject method of the DatabaseLoaderDisplay.py script.

2020-11-04 20:00 UTC, zrhernan commented on build/lib.linux-x86_64-2.7/patientalloc/src/Database/Subject/SubjectFactory.py
>  import patientalloc
Yes I have added 'build' to the .gitignore file.

2020-11-04 20:00 UTC, zrhernan commented on patientalloc/src/Database/Database.py
> +        # print(self.entries)
Will do, I'll remove any commented code remaining in the files.

2020-11-04 20:00 UTC, zrhernan commented on patientalloc/src/GUI/GUI.py
> +        viewmode = self.getViewMode()
I understand this, however this was a feature Jose specifically asked to add to the code. Where an option is given at the start of the allocation program whether to view all relevant information related to group placement of the new subject entry (probabilities when placed in either group for all fields/by each field and option to switch groups) or not view any information at all so as to keep the subject blind to the group placement. My understanding is that you can only create a database in the admin mode. If you have any suggestions on this or anything to correct that I said, please feel free to message back.

2020-11-05 11:39 UTC, Ruijan approved these changes
All good to me. Thank you for taking my comments into account.
Are you going to deploy this code to the Beau-séjour clinic? If yes, you will have to rename a lot of files because of your change from "reaching" to "extension".
Don't hesitate to contact me directly if you need: rechenmann@gmail.com

2020-11-05 11:39 UTC, Ruijan commented on patientalloc/src/Database/Subject/SubjectFactory.py
> +        self.gui = currentGui
Perfect. Thanks!

2020-11-05 11:41 UTC, Ruijan commented on patientalloc/src/GUI/GUI.py
> +        viewmode = self.getViewMode()
If the requirements changed then it's fine.

2020-11-05 19:48 UTC, zrhernan reviewed
I believe I changed changed the 'reaching' string back to 'extension'. In addition I also reverted the directory paths in GUISettings back to their original paths. They should all be in the latest commit.

2020-11-05 19:48 UTC, zrhernan commented on patientalloc/src/GUI/GUISettings.py
> +        xml_file_path = str(Path.home()) + "/StrokeMI/protocolxmls/"
I'll need to change these back to their original filepaths

2021-01-20 18:14 UTC, zrhernan commented
I think this still needs to be merged. It doesn't seem to have ever been merged yet.

2021-01-20 20:36 UTC, closed without merging